<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>0.1.0</Version>
    <Authors>Lincube</Authors>
    <Product>TinadecManger</Product>
    <Copyright>Copyright (c) 2026 Lincube</Copyright>
  </PropertyGroup>
</Project>
